{% set name = "bbhash" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bbhash-{{ version }}.tar.gz
  sha256: 2a7d39c4d92713ea6b0423d939882350ba1f94900e8b0d49859e66f2628cd7d5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [win or py<311]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - cython >=3.1.6
    - setuptools >=74.1
    - python
    - numpy
    - pip
  run:
    - python

test:
  imports:
    - bbhash
    - bbhash_table
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/test_table.py
    - tests/test_bbhash.py

about:
  home: http://github.com/dib-lab/pybbhash
  summary: A Python wrapper for the BBHash Minimal Perfect Hash Function
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ctb
    - luizirber
